name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
          cache-dependency-path: src/homeconnect_ws_sim/frontend/package-lock.json
      - run: |
          cd src/homeconnect_ws_sim/frontend
          npm ci
      - run: |
          cd src/homeconnect_ws_sim/frontend
          npm run build
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
      - name: Build package
        run: uv build
      - uses: svenstaro/upload-release-action@v2
        if: ${{ github.event_name == 'release' }}
        with:
          file: dist/*.whl
          file_glob: true
